FROM tursoft/pardus:17.4-SERVER-amd64
MAINTAINER Muhammet Turşak (tursoft@gmail.com)
LABEL maintainer="Muhammet Turşak (tursoft@gmail.com)"

ENTRYPOINT echo "=== PARDUS'dan Merhabalar... ====" && cat /etc/os-release && echo "====================="
