FROM tursoft/pardus:17.4-SERVER-amd64
MAINTAINER Muhammet Turşak (tursoft@gmail.com)

# ===============================================================
# REF: 
# ===============================================================
