FROM tursoft/pardus
MAINTAINER Ömer SAVAŞ (iletisim@omersavas.com)
LABEL maintainer="Ömer SAVAŞ (iletisim@omersavas.com)"

RUN apt-get update
RUN apt-get install python=2.7.13-2 -y
RUN apt-get install python-pip=9.0.1-2 -y