FROM tursoft/pardus-dotnetcore:2.2.104-sdk AS build
MAINTAINER Muhammet Turşak (tursoft@gmail.com)
LABEL maintainer="Muhammet Turşak (tursoft@gmail.com)"

# ===============================================================
# REF: https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile
# ===============================================================

# Build =======================
RUN echo "================================="
RUN echo "İşletim Sistemi"
RUN echo "================================="
RUN cat /etc/os-release
RUN echo "================================="

WORKDIR /app

# copy csproj and restore as distinct layers
COPY dotnetapp/*.csproj ./dotnetapp/
COPY utils/*.csproj ./utils/
WORKDIR /app/dotnetapp
RUN dotnet restore

# copy and publish app and libraries
WORKDIR /app/
COPY dotnetapp/. ./dotnetapp/
COPY utils/. ./utils/
WORKDIR /app/dotnetapp
RUN dotnet publish -c Release -o out


# test application -- see: dotnet-docker-unit-testing.md
FROM build AS testrunner
WORKDIR /app/tests
COPY tests/. .

RUN echo "================================="
RUN echo "İşletim Sistemi"
RUN echo "================================="
RUN cat /etc/os-release
RUN echo "================================="

ENTRYPOINT ["dotnet", "test", "--logger:trx"]


# Runtime =======================
FROM tursoft/pardus-dotnetcore:2.2.2 AS runtime
WORKDIR /app
COPY --from=build /app/dotnetapp/out ./

RUN echo "================================="
RUN echo "İşletim Sistemi"
RUN echo "================================="
RUN cat /etc/os-release
RUN echo "================================="
ENTRYPOINT ["dotnet", "dotnetapp.dll"]