version: '3.1'

networks:
  testnetwork:

services:

  dotnet_sdk_ornek:
    image: tursoft/pardus-dotnetcore:2.2.104-sdk-ornek
    command:
      - 'sleep infinity'    
    networks:
      - testnetwork    