FROM tursoft/pardus:17.4-SERVER-amd64
LABEL maintainer="Ibrahim ÇOBANİ (ibrahim@b1.com.tr)"
# gcc for cgo
RUN apt-get update && apt-get install -y --no-install-recommends \
		g++ \
		gcc \
		libc6-dev \
		make \
		pkg-config \
	&& rm -rf /var/lib/apt/lists/*

ENV GOLANG_VERSION 1.12

RUN apt-get update
RUN curl -SL --insecure --output go.tar.gz https://dl.google.com/go/go1.12.linux-amd64.tar.gz
RUN tar -xvf go.tar.gz
RUN mv go /usr/local


ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH